### ISSUE TITLE
Can't enable extension from commandline 

### ISSUE THREAD

**Issue by stuaxo** [fomightez/cairo-jupyter#3]
Trying enable the extension from the commandline causes an error message.

This might be because I'm a little unclear on Jupyter / ipython terminology -

Are we at nbextension, a server extension or something else.

Need to jump on the Jupyter gitter chat and ask how to fix this.

@formightez feel free to assign extension bugs to me :)

- might be worth making a Github label for extension bugs

**Comment by fomightez** [comment]
Created `extension` label.

**Comment by stuaxo** [comment]
Seems like I had been experimenting with re-orgranising the extension on my local computer, must upload this :)

**Comment by stuaxo** [comment]
Fixed in PR #11
